// Serverless endpoint that returns the SPA shell with Open Graph / Twitter
// meta tags pre-rendered so WhatsApp, iMessage, Facebook, Twitter, etc. show
// the cover image and the invitation title with the pretty typography (the
// image generated by /api/og uses the Fraunces italic font).
//
// We fetch the published index.html from the same deployment (so we always
// pick up Vite's hashed asset filenames), look up the event by slug, and
// inject the meta tags into <head>. The SPA still hydrates normally for
// real users because the body / scripts are unchanged.

import { admin } from './_lib/supa.js'

function escapeHtml(value = '') {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

function formatDate(value) {
  if (!value) return ''
  try {
    return new Intl.DateTimeFormat('es-GT', {
      day: '2-digit',
      month: 'long',
      year: 'numeric',
    }).format(new Date(value))
  } catch {
    return ''
  }
}

async function loadShell(origin) {
  // Read the built index.html so we keep Vite's hashed asset URLs.
  const res = await fetch(`${origin}/index.html`, {
    headers: { 'x-inyeon-shell': '1' },
  })
  if (!res.ok) throw new Error(`shell ${res.status}`)
  return res.text()
}

export default async function handler(req, res) {
  try {
    const host = req.headers['x-forwarded-host'] || req.headers.host
    const proto = req.headers['x-forwarded-proto'] || 'https'
    const origin = `${proto}://${host}`

    const slug = (req.query?.slug || '').toString()
    if (!slug) {
      // Fallback: just serve the normal shell.
      const html = await loadShell(origin)
      res.setHeader('Content-Type', 'text/html; charset=utf-8')
      return res.status(200).send(html)
    }

    let event = null
    try {
      const supa = admin()
      const { data } = await supa
        .from('events')
        .select('slug, title, subtitle, event_date, cover_image_url')
        .eq('slug', slug)
        .maybeSingle()
      event = data || null
    } catch {
      event = null
    }

    const shell = await loadShell(origin)

    const title = event?.title || 'Inyeon · Invitación digital'
    const dateStr = formatDate(event?.event_date)
    const description =
      event?.subtitle ||
      (dateStr ? `Te invitamos · ${dateStr}` : 'Te invitamos a celebrar con nosotros')

    const pageUrl = `${origin}/i/${encodeURIComponent(slug)}`
    const ogImage = `${origin}/api/og?slug=${encodeURIComponent(slug)}`

    const meta = `
    <title>${escapeHtml(title)}</title>
    <meta name="description" content="${escapeHtml(description)}" />
    <link rel="canonical" href="${escapeHtml(pageUrl)}" />

    <meta property="og:type" content="website" />
    <meta property="og:site_name" content="Inyeon" />
    <meta property="og:title" content="${escapeHtml(title)}" />
    <meta property="og:description" content="${escapeHtml(description)}" />
    <meta property="og:url" content="${escapeHtml(pageUrl)}" />
    <meta property="og:image" content="${escapeHtml(ogImage)}" />
    <meta property="og:image:secure_url" content="${escapeHtml(ogImage)}" />
    <meta property="og:image:type" content="image/png" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />
    <meta property="og:image:alt" content="${escapeHtml(title)}" />
    <meta property="og:locale" content="es_GT" />

    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="${escapeHtml(title)}" />
    <meta name="twitter:description" content="${escapeHtml(description)}" />
    <meta name="twitter:image" content="${escapeHtml(ogImage)}" />
`

    // Replace the existing <title> (and inject meta tags right before </head>)
    let html = shell.replace(/<title>[\s\S]*?<\/title>/i, '')
    html = html.replace('</head>', `${meta}\n  </head>`)

    res.setHeader('Content-Type', 'text/html; charset=utf-8')
    res.setHeader(
      'Cache-Control',
      'public, max-age=0, s-maxage=60, stale-while-revalidate=600'
    )
    return res.status(200).send(html)
  } catch (err) {
    res.setHeader('Content-Type', 'text/html; charset=utf-8')
    return res.status(500).send(`<!doctype html><meta charset="utf-8"><pre>${escapeHtml(err.message || 'error')}</pre>`)
  }
}
